#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Update the recipe availability table in README.md."""

from __future__ import annotations

from dataclasses import dataclass
from html import escape
from pathlib import Path
from urllib.parse import quote

HOPPER_GPUS_STR = "H100 / H200"
BLACKWELL_GPUS_STR = "B200 / B300"
GRACE_BLACKWELL_GPUS_STR = "GB200 / GB300"


REPO_ROOT = Path(__file__).resolve().parents[1]
README_PATH = REPO_ROOT / "README.md"
RECIPES_ROOT = REPO_ROOT / "recipes"

START_MARKER = "<!-- recipe-table:start -->"
END_MARKER = "<!-- recipe-table:end -->"
GENERATED_NOTE = (
    "<!-- This section is generated by `python scripts/update_recipe_table.py`. -->"
)
REFRESH_INSTRUCTION = (
    "Run `python scripts/update_recipe_table.py` after adding or removing recipe "
    "directories."
)

NODE_ORDER = ("multi-node", "single-node")
NODE_TITLES = {
    "multi-node": "Multi-Node",
    "single-node": "Single-Node",
}
GREEN_CHECK = "&#9989;"
YELLOW_CAUTION = "&#9888;&#65039;"
EM_DASH = "&#10134;"

# (model, gpu-column) cells that cannot run on a single node — the weights don't
# fit in one node's HBM, so the deployment must span multiple nodes. These render
# as a dash (linking to the multi-node recipe when one exists) in the
# single-node table instead of the "in progress" caution marker.
MULTINODE_ONLY = {
    ("DeepSeek-R1", HOPPER_GPUS_STR),
    ("DeepSeek-V4-Pro", HOPPER_GPUS_STR),
    ("Kimi-K2.5", HOPPER_GPUS_STR),
}
MULTINODE_ONLY_TITLE = "Does not fit on a single node — use the multi-node recipe"

# (model, gpu-column) cells in the multi-node table that are not supported on a
# given platform. These render as a dash (no link) instead of the "in progress"
# caution marker.
PLATFORM_NA = {
    ("GLM-5", BLACKWELL_GPUS_STR),
    ("GLM-5", HOPPER_GPUS_STR),
    ("MiniMax-M2.5", HOPPER_GPUS_STR),
    # gpt-oss-120b fits on a single node; multi-node serving is not offered on
    # these platforms.
    ("gpt-oss-120b", BLACKWELL_GPUS_STR),
    ("gpt-oss-120b", HOPPER_GPUS_STR),
    ("DeepSeek-V4-Pro", BLACKWELL_GPUS_STR),
    # Kimi-K2.5 multi-node serving is only offered on Grace-Blackwell.
    ("Kimi-K2.5", BLACKWELL_GPUS_STR),
    ("Kimi-K2.5", HOPPER_GPUS_STR),
}
PLATFORM_NA_TITLE = "Not supported on this platform"

# Grace-Blackwell (GB200 / GB300) systems are rack-scale, so they are only
# represented in the Multi-Node table. The Single-Node table never shows a
# GB200 / GB300 column.
SINGLE_NODE_EXCLUDED_COLUMNS = {GRACE_BLACKWELL_GPUS_STR}

# Model directories that differ only by a trailing precision token are merged
# into a single table row, with the precision shown next to the checkmark per
# GPU column (e.g. ...-Super-120B-A12B-NVFP4 + ...-Super-120B-A12B-FP8 become
# one "...-Super-120B-A12B" row reading FP4 on B200/B300 and FP8 on H100/H200).
PRECISION_SUFFIXES = {
    "NVFP4": "NVFP4",
    "FP4": "FP4",
    "FP8": "FP8",
    "FP16": "FP16",
    "BF16": "BF16",
}

GPU_COLUMN_GROUPS = {
    # Group H100 and H200 together for similar recipes
    "H100": HOPPER_GPUS_STR,
    "H200": HOPPER_GPUS_STR,

    # Group B200 and B300 together for similar recipes
    "B200": BLACKWELL_GPUS_STR,
    "B300": BLACKWELL_GPUS_STR,

    # Group GB200 and GB300 together for similar recipes
    "GB200": GRACE_BLACKWELL_GPUS_STR,
    "GB300": GRACE_BLACKWELL_GPUS_STR,
}

GPU_COLUMN_ORDER = (GRACE_BLACKWELL_GPUS_STR, BLACKWELL_GPUS_STR, HOPPER_GPUS_STR)


@dataclass(frozen=True)
class RecipeRow:
    node_count: str
    model: str
    base_model: str
    precision: str | None
    gpu: str
    gpu_dir: Path
    has_recipe_dirs: bool


def split_precision(model_name: str) -> tuple[str, str | None]:
    base, _, last = model_name.rpartition("-")
    if base and last.upper() in PRECISION_SUFFIXES:
        return base, PRECISION_SUFFIXES[last.upper()]
    return model_name, None


def sort_key(value: str, preferred_order: tuple[str, ...]) -> tuple[int, str]:
    try:
        return (preferred_order.index(value), value.lower())
    except ValueError:
        return (len(preferred_order), value.lower())


def relative_link(path: Path) -> str:
    relative = path.relative_to(REPO_ROOT).as_posix()
    return quote(relative + "/", safe="/-._")


def discover_recipe_rows() -> list[RecipeRow]:
    if not RECIPES_ROOT.is_dir():
        return []

    rows: list[RecipeRow] = []
    node_dirs = sorted(
        (path for path in RECIPES_ROOT.iterdir() if path.is_dir()),
        key=lambda path: sort_key(path.name, NODE_ORDER),
    )

    for node_dir in node_dirs:
        model_dirs = sorted(
            (path for path in node_dir.iterdir() if path.is_dir()),
            key=lambda path: path.name.lower(),
        )
        for model_dir in model_dirs:
            gpu_dirs = sorted(
                (path for path in model_dir.iterdir() if path.is_dir()),
                key=lambda path: path.name.lower(),
            )
            base_model, precision = split_precision(model_dir.name)
            for gpu_dir in gpu_dirs:
                rows.append(
                    RecipeRow(
                        node_count=node_dir.name,
                        model=model_dir.name,
                        base_model=base_model,
                        precision=precision,
                        gpu=gpu_dir.name,
                        gpu_dir=gpu_dir,
                        has_recipe_dirs=any(
                            path.is_dir() for path in gpu_dir.iterdir()
                        ),
                    )
                )

    return rows


def display_title(node_count: str) -> str:
    return NODE_TITLES.get(
        node_count, "-".join(part.capitalize() for part in node_count.split("-"))
    )


def gpu_column(gpu: str) -> str:
    return GPU_COLUMN_GROUPS.get(gpu, gpu)


def cell_link_path(rows: list[RecipeRow]) -> Path | None:
    available = [row for row in rows if row.has_recipe_dirs]
    if not available:
        return None
    if len(available) == 1:
        return available[0].gpu_dir
    return available[0].gpu_dir.parent


def gpu_cell(
    rows: list[RecipeRow],
    node_count: str,
    model: str,
    column: str,
    multinode_link: Path | None,
) -> str:
    link_path = cell_link_path(rows)
    if link_path is not None:
        href = escape(relative_link(link_path), quote=True)
        precisions = sorted(
            {row.precision for row in rows if row.has_recipe_dirs and row.precision}
        )
        label = f' {escape(" / ".join(precisions))}' if precisions else ""
        return f'<a href="{href}">{GREEN_CHECK}</a>{label}'

    if node_count == "single-node" and (model, column) in MULTINODE_ONLY:
        title = escape(MULTINODE_ONLY_TITLE, quote=True)
        if multinode_link is not None:
            href = escape(relative_link(multinode_link), quote=True)
            return f'<a href="{href}" title="{title}">{EM_DASH}</a>'
        return f'<span title="{title}">{EM_DASH}</span>'

    if node_count == "multi-node" and (model, column) in PLATFORM_NA:
        title = escape(PLATFORM_NA_TITLE, quote=True)
        return f'<span title="{title}">{EM_DASH}</span>'

    return YELLOW_CAUTION


def render_node_table(
    node_count: str,
    rows: list[RecipeRow],
    multinode_links: dict[tuple[str, str], Path],
) -> list[str]:
    models = sorted(
        {row.base_model for row in rows if row.has_recipe_dirs},
        key=str.lower,
    )
    if not models:
        return []

    columns = sorted(
        {gpu_column(row.gpu) for row in rows},
        key=lambda column: sort_key(column, GPU_COLUMN_ORDER),
    )
    if node_count == "single-node":
        columns = [
            column for column in columns if column not in SINGLE_NODE_EXCLUDED_COLUMNS
        ]
    rows_by_model_and_column: dict[tuple[str, str], list[RecipeRow]] = {}
    for row in rows:
        rows_by_model_and_column.setdefault(
            (row.base_model, gpu_column(row.gpu)), []
        ).append(row)

    lines = [
        f"### {escape(display_title(node_count))}",
        "",
        "<table>",
        "  <thead>",
        "    <tr>",
        "      <th>Model</th>",
        *[f"      <th><code>{escape(column)}</code></th>" for column in columns],
        "    </tr>",
        "  </thead>",
        "  <tbody>",
    ]

    for model in models:
        lines.extend(
            [
                "    <tr>",
                f"      <td><code>{escape(model)}</code></td>",
                *[
                    (
                        "      <td>"
                        f"{gpu_cell(rows_by_model_and_column.get((model, column), []), node_count, model, column, multinode_links.get((model, column)))}"
                        "</td>"
                    )
                    for column in columns
                ],
                "    </tr>",
            ]
        )

    lines.extend(
        [
            "  </tbody>",
            "</table>",
        ]
    )
    return lines


def render_table(rows: list[RecipeRow]) -> str:
    lines = [
        START_MARKER,
        GENERATED_NOTE,
    ]
    sections: list[list[str]] = []

    multinode_links: dict[tuple[str, str], Path] = {}
    multinode_grouped: dict[tuple[str, str], list[RecipeRow]] = {}
    for row in rows:
        if row.node_count == "multi-node":
            multinode_grouped.setdefault(
                (row.base_model, gpu_column(row.gpu)), []
            ).append(row)
    for key, grouped_rows in multinode_grouped.items():
        link_path = cell_link_path(grouped_rows)
        if link_path is not None:
            multinode_links[key] = link_path

    for node_count in NODE_ORDER:
        node_rows = [row for row in rows if row.node_count == node_count]
        node_table = render_node_table(node_count, node_rows, multinode_links)
        if node_table:
            sections.append(node_table)

    extra_node_counts = sorted(
        {row.node_count for row in rows if row.node_count not in NODE_ORDER},
        key=str.lower,
    )
    for node_count in extra_node_counts:
        node_rows = [row for row in rows if row.node_count == node_count]
        node_table = render_node_table(node_count, node_rows, multinode_links)
        if node_table:
            sections.append(node_table)

    for section in sections:
        lines.extend(["", *section])

    lines.extend(
        [
            END_MARKER,
        ]
    )
    return "\n".join(lines)


def replace_between_markers(readme: str, table: str) -> str:
    start = readme.find(START_MARKER)
    end = readme.find(END_MARKER)
    if start == -1 or end == -1:
        raise ValueError("recipe table markers were not found")
    if start > end:
        raise ValueError("recipe table markers are out of order")

    end += len(END_MARKER)
    return f"{readme[:start]}{table}{readme[end:]}"


def replace_legacy_model_block(readme: str, table: str) -> str:
    legacy_heading = "Current model directories:"
    next_section = "Each leaf directory is reserved"

    start = readme.find(legacy_heading)
    end = readme.find(next_section)
    if start == -1 or end == -1 or start > end:
        raise ValueError(
            "could not find recipe table markers or the legacy model directory block"
        )

    replacement = f"Current recipes:\n\n{REFRESH_INSTRUCTION}\n\n{table}\n\n"
    return f"{readme[:start]}{replacement}{readme[end:]}"


def update_readme() -> None:
    rows = discover_recipe_rows()
    table = render_table(rows)
    readme = README_PATH.read_text(encoding="utf-8")

    if START_MARKER in readme or END_MARKER in readme:
        updated = replace_between_markers(readme, table)
    else:
        updated = replace_legacy_model_block(readme, table)

    if updated != readme:
        README_PATH.write_text(updated, encoding="utf-8")


if __name__ == "__main__":
    update_readme()
