#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Update the AgentX tables in README.md and recipes/multi-node/AGENTX.md.

AgentX recipes live at ``recipes/<node-count>/<model>/<gpu>/<framework>/agentic/``
and are keyed off the agentic-coding (cc-traces-weka) workload rather than a
fixed ISL/OSL sweep, so they are counted separately from the support matrix.

README.md gets the support-matrix view; the AGENTX.md next to each node-count
tree gets the per-recipe index with the InferenceX source link that is stamped
in each YAML header.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from html import escape
from os.path import relpath
from pathlib import Path
from urllib.parse import quote

HOPPER_GPUS_STR = "H100 / H200"
BLACKWELL_GPUS_STR = "B200 / B300"
GRACE_BLACKWELL_GPUS_STR = "GB200 / GB300"

REPO_ROOT = Path(__file__).resolve().parents[1]
README_PATH = REPO_ROOT / "README.md"
RECIPES_ROOT = REPO_ROOT / "recipes"

START_MARKER = "<!-- agentx-table:start -->"
END_MARKER = "<!-- agentx-table:end -->"
INDEX_START_MARKER = "<!-- agentx-index:start -->"
INDEX_END_MARKER = "<!-- agentx-index:end -->"
GENERATED_NOTE = (
    "<!-- This section is generated by `python scripts/update_agentx_table.py`. -->"
)

SOURCE_URL_RE = re.compile(r"^#\s+(https://\S+)", re.MULTILINE)
CONCURRENCIES_RE = re.compile(r"^#\s+Concurrencies:\s*(.+)$", re.MULTILINE)
PRECISION_RE = re.compile(r"""precision:\s*["']?([A-Za-z0-9]+)""")
SPEC_METHOD_RE = re.compile(r'"method"\s*:\s*"([A-Za-z0-9_.-]+)"')
UNKNOWN = "&mdash;"

NODE_ORDER = ("multi-node", "single-node")
NODE_TITLES = {
    "multi-node": "Multi-Node",
    "single-node": "Single-Node",
}


def index_path(node_count: str) -> Path:
    return RECIPES_ROOT / node_count / "AGENTX.md"


GREEN_CHECK = "&#9989;"
EM_DASH = "&#10134;"
NOT_PORTED_TITLE = "No AgentX recipe ported for this platform"

GPU_COLUMN_GROUPS = {
    "H100": HOPPER_GPUS_STR,
    "H200": HOPPER_GPUS_STR,
    "B200": BLACKWELL_GPUS_STR,
    "B300": BLACKWELL_GPUS_STR,
    "GB200": GRACE_BLACKWELL_GPUS_STR,
    "GB300": GRACE_BLACKWELL_GPUS_STR,
}
GPU_COLUMN_ORDER = (GRACE_BLACKWELL_GPUS_STR, BLACKWELL_GPUS_STR, HOPPER_GPUS_STR)
FRAMEWORK_ORDER = ("vllm", "sglang", "trtllm")


@dataclass(frozen=True)
class AgentXDir:
    node_count: str
    model: str
    gpu: str
    framework: str
    path: Path
    count: int


def discover() -> list[AgentXDir]:
    found: list[AgentXDir] = []
    if not RECIPES_ROOT.is_dir():
        return found
    for agentic_dir in sorted(RECIPES_ROOT.glob("*/*/*/*/agentic")):
        if not agentic_dir.is_dir():
            continue
        count = len(list(agentic_dir.glob("*.yaml")))
        if not count:
            continue
        framework = agentic_dir.parent.name
        gpu = agentic_dir.parent.parent.name
        model = agentic_dir.parent.parent.parent.name
        node_count = agentic_dir.parent.parent.parent.parent.name
        found.append(
            AgentXDir(node_count, model, gpu, framework, agentic_dir, count)
        )
    return found


def recipe_metadata(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    name = path.name.lower()

    source = SOURCE_URL_RE.search(text)
    precision = PRECISION_RE.search(text)

    if "decode_nodes" in text or "decode_workers" in text:
        mode = "disagg"
    elif "agg_nodes" in text or "agg_workers" in text:
        mode = "agg"
    else:
        mode = UNKNOWN

    if "mtp2" in name:
        spec = "MTP2"
    elif "mtp" in name:
        spec = "MTP"
    else:
        method = SPEC_METHOD_RE.search(text)
        spec = method.group(1) if method else "none"

    concurrencies = CONCURRENCIES_RE.search(text)

    return {
        "source": source.group(1) if source else "",
        "precision": precision.group(1).upper() if precision else UNKNOWN,
        "mode": mode,
        "spec": spec,
        "concurrencies": concurrencies.group(1).strip() if concurrencies else "",
    }


def render_index(entries: list[AgentXDir], index: Path) -> str:
    lines = [INDEX_START_MARKER, GENERATED_NOTE]

    recipes_by_model: dict[str, list[tuple[AgentXDir, Path]]] = {}
    for entry in entries:
        for yaml_path in entry.path.glob("*.yaml"):
            recipes_by_model.setdefault(entry.model, []).append((entry, yaml_path))

    # Single-node recipes sweep concurrency inside the file, so the index shows
    # the points each one covers; multi-node recipes are one point each.
    metadata = {
        yaml_path: recipe_metadata(yaml_path)
        for recipes in recipes_by_model.values()
        for _, yaml_path in recipes
    }
    show_conc = any(meta["concurrencies"] for meta in metadata.values())

    for model in sorted(recipes_by_model, key=str.lower):
        recipes = sorted(
            recipes_by_model[model],
            key=lambda item: (
                sort_key(item[0].gpu, GPU_COLUMN_ORDER),
                item[0].gpu,
                sort_key(item[0].framework, FRAMEWORK_ORDER),
                item[1].name.lower(),
            ),
        )
        columns = ["Recipe", "GPU", "Framework", "Mode", "Precision", "Spec"]
        if show_conc:
            columns.append("Concurrencies")
        columns.append("InferenceX")
        lines.extend(
            [
                "",
                f"### {model}",
                "",
                "| " + " | ".join(columns) + " |",
                "|" + "---|" * len(columns),
            ]
        )
        for entry, yaml_path in recipes:
            meta = metadata[yaml_path]
            local = quote(
                relpath(yaml_path, index.parent).replace("\\", "/"), safe="/-._"
            )
            source = f"[source]({meta['source']})" if meta["source"] else UNKNOWN
            cells = [
                f"[`{yaml_path.name}`]({local})",
                entry.gpu,
                entry.framework,
                meta["mode"],
                meta["precision"],
                meta["spec"],
            ]
            if show_conc:
                cells.append(f"`{meta['concurrencies']}`" if meta["concurrencies"] else UNKNOWN)
            cells.append(source)
            lines.append("| " + " | ".join(cells) + " |")

    lines.append(INDEX_END_MARKER)
    return "\n".join(lines)


def relative_link(path: Path) -> str:
    relative = path.relative_to(REPO_ROOT).as_posix()
    return quote(relative + "/", safe="/-._")


def sort_key(value: str, preferred: tuple[str, ...]) -> tuple[int, str]:
    try:
        return (preferred.index(value), value.lower())
    except ValueError:
        return (len(preferred), value.lower())


def cell(entries: list[AgentXDir]) -> str:
    if not entries:
        title = escape(NOT_PORTED_TITLE, quote=True)
        return f'<span title="{title}">{EM_DASH}</span>'

    gpu_dirs = {entry.path.parent.parent for entry in entries}
    link_path = next(iter(gpu_dirs)) if len(gpu_dirs) == 1 else entries[0].path.parents[2]
    href = escape(relative_link(link_path), quote=True)

    per_framework: dict[str, int] = defaultdict(int)
    for entry in entries:
        per_framework[entry.framework] += entry.count
    frameworks = sorted(
        per_framework, key=lambda name: sort_key(name, FRAMEWORK_ORDER)
    )
    detail = ", ".join(f"{escape(name)} {per_framework[name]}" for name in frameworks)
    return f'<a href="{href}">{GREEN_CHECK}</a> {detail}'


def render_node_table(node_count: str, entries: list[AgentXDir]) -> list[str]:
    models = sorted({entry.model for entry in entries}, key=str.lower)
    if not models:
        return []

    columns = sorted(
        {GPU_COLUMN_GROUPS.get(entry.gpu, entry.gpu) for entry in entries},
        key=lambda column: sort_key(column, GPU_COLUMN_ORDER),
    )

    grouped: dict[tuple[str, str], list[AgentXDir]] = defaultdict(list)
    for entry in entries:
        grouped[(entry.model, GPU_COLUMN_GROUPS.get(entry.gpu, entry.gpu))].append(entry)

    lines = [
        f"### {escape(NODE_TITLES.get(node_count, node_count))}",
        "",
        "<table>",
        "  <thead>",
        "    <tr>",
        "      <th>Model</th>",
        *[f"      <th><code>{escape(column)}</code></th>" for column in columns],
        "      <th>Total</th>",
        "    </tr>",
        "  </thead>",
        "  <tbody>",
    ]

    for model in models:
        total = sum(entry.count for entry in entries if entry.model == model)
        lines.extend(
            [
                "    <tr>",
                f"      <td><code>{escape(model)}</code></td>",
                *[
                    f"      <td>{cell(grouped.get((model, column), []))}</td>"
                    for column in columns
                ],
                f"      <td>{total}</td>",
                "    </tr>",
            ]
        )

    lines.extend(["  </tbody>", "</table>"])
    return lines


def render_table(entries: list[AgentXDir]) -> str:
    lines = [START_MARKER, GENERATED_NOTE]
    for node_count in NODE_ORDER:
        node_entries = [entry for entry in entries if entry.node_count == node_count]
        section = render_node_table(node_count, node_entries)
        if section:
            lines.extend(["", *section])
    lines.append(END_MARKER)
    return "\n".join(lines)


def splice(path: Path, block: str, start_marker: str, end_marker: str) -> bool:
    text = path.read_text(encoding="utf-8")
    start = text.find(start_marker)
    end = text.find(end_marker)
    if start == -1 or end == -1:
        raise SystemExit(f"AgentX markers were not found in {path.name}")
    if start > end:
        raise SystemExit(f"AgentX markers are out of order in {path.name}")

    updated = f"{text[:start]}{block}{text[end + len(end_marker):]}"
    if updated == text:
        return False
    path.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    entries = discover()
    total = sum(entry.count for entry in entries)

    changed = splice(README_PATH, render_table(entries), START_MARKER, END_MARKER)
    for node_count in NODE_ORDER:
        node_entries = [entry for entry in entries if entry.node_count == node_count]
        index = index_path(node_count)
        if not node_entries or not index.is_file():
            continue
        changed |= splice(
            index,
            render_index(node_entries, index),
            INDEX_START_MARKER,
            INDEX_END_MARKER,
        )

    print(
        f"{'updated' if changed else 'already up to date'}: {total} AgentX recipes"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
